pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:this-work/scss-framework.git
          - cd scss-framework
          - git push --mirror git@github.com:this-work/scss-framework.git
    - step:
          name: 'Linting Code'
          image: node:16
          script:
              - npm install
              - npm run documentation-build
              - npm run linting
          artifacts:
              - documentation/**
              - src/**
#        - step:
#              name: 'Commit Code Changes'
#              image: node:16
#              script:
#                  - git remote set-url origin https://${APP_SECRET_USER}:${APP_SECRET}@bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}
#                  - git add -A
#                  - git commit -m "[skip ci] Updating Documentation & Autofixed Linted Code"
#                  - git push