pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:this-work/scss-framework.git
          - cd scss-framework.git
          - git push --mirror git@github.com:this-work/scss-framework.git
    - step:
          name: 'Linting Code'
          image: node:20
          script:
              - npm install
              - npm run linting
          artifacts:
              - documentation/**
              - src/**
