pipelines:
    default:
        - step:
              name: 'Linting Code & Update Documentation'
              image: node:16
              script:
                  - npm install
                  - npm run documentation-build
                  - npm run linting
              artifacts:
                  - documentation/**
                  - src/**
        - step:
              name: 'Commit Code Changes'
              image: node:16
              script:
                  - git remote set-url origin https://thiswoestmann:${APP_SECRET}@bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}
                  - git ls-files --modified | xargs git add -A
                  - git ls-files --modified | xargs git commit -m "[skip ci] Updating Documentation & Autofixed Linted Code"
                  - git ls-files --modified | xargs git push
